### ISSUE TITLE
MessagingTest/MessagingBase CDC-test fails

### ISSUE THREAD

**Issue by asn25** [microservices-patterns/ftgo-application#65]
Hi,

producer-side CDC-test for Order Service (MessagingTest/MessagingBase) fails. See log below.

Seems it's about serialization of Money class. 

If I add CommonConfiguration to MessagingBase.TestConfiguration config, then tess passes OK:

public abstract class MessagingBase {
  @Configuration
  @EnableAutoConfiguration
  @Import({EventuateContractVerifierConfiguration.class,  TramEventsPublisherConfiguration.class, 				  TramInMemoryConfiguration.class, **CommonConfiguration.class** })
  public static class TestConfiguration {

===========

2019-12-26 12:18:34.724  INFO [ftgo-order-service,,,] 3052 --- [           main] i.e.t.inmemory.InMemoryMessageProducer   : No transaction active
2019-12-26 12:18:34.751  INFO [ftgo-order-service,85e049c3b2a9337c,85e049c3b2a9337c,true] 3052 --- [           main] i.e.t.inmemory.InMemoryMessageConsumer   : sending to channel net.chrisrichardson.ftgo.orderservice.domain.Order that has 0 subscriptions this message io.eventuate.tram.messaging.common.MessageImpl@3b66ac74[payload={"orderDetails":{"lineItems":[{"quantity":5,"menuItemId":"1","name":"Chicken Vindaloo","price":{},"total":{}}],"orderTotal":{},"restaurantId":1,"consumerId":1511300065921},"restaurantName":"Ajanta"},headers={PARTITION_ID=99, event-aggregate-type=net.chrisrichardson.ftgo.orderservice.domain.Order, DATE=Thu, 26 Dec 2019 09:18:34 GMT, event-aggregate-id=99, X-B3-SpanId=85e049c3b2a9337c, event-type=net.chrisrichardson.ftgo.orderservice.api.events.OrderCreatedEvent, DESTINATION=net.chrisrichardson.ftgo.orderservice.domain.Order, X-B3-Sampled=1, X-B3-TraceId=85e049c3b2a9337c, ID=0000016f418024dc-14dae921faa80000}] 
2019-12-26 12:18:34.773  INFO [ftgo-order-service,85e049c3b2a9337c,85e049c3b2a9337c,true] 3052 --- [           main] i.e.t.inmemory.InMemoryMessageConsumer   : sending to wildcard channel net.chrisrichardson.ftgo.orderservice.domain.Order that has 1 subscriptions this message io.eventuate.tram.messaging.common.MessageImpl@3b66ac74[payload={"orderDetails":{"lineItems":[{"quantity":5,"menuItemId":"1","name":"Chicken Vindaloo","price":{},"total":{}}],"orderTotal":{},"restaurantId":1,"consumerId":1511300065921},"restaurantName":"Ajanta"},headers={PARTITION_ID=99, event-aggregate-type=net.chrisrichardson.ftgo.orderservice.domain.Order, DATE=Thu, 26 Dec 2019 09:18:34 GMT, event-aggregate-id=99, X-B3-SpanId=85e049c3b2a9337c, event-type=net.chrisrichardson.ftgo.orderservice.api.events.OrderCreatedEvent, DESTINATION=net.chrisrichardson.ftgo.orderservice.domain.Order, X-B3-Sampled=1, X-B3-TraceId=85e049c3b2a9337c, ID=0000016f418024dc-14dae921faa80000}] 
2019-12-26 12:18:34.961 TRACE [ftgo-order-service,85e049c3b2a9337c,fc051af18901d24a,true] 3052 --- [pool-1-thread-1] i.e.t.c.c.DecoratedMessageHandlerFactory : Invoking handler io.eventuate.tram.springcloudcontractsupport.EventuateTramMessageVerifier 0000016f418024dc-14dae921faa80000
2019-12-26 12:18:34.962 TRACE [ftgo-order-service,85e049c3b2a9337c,fc051af18901d24a,true] 3052 --- [pool-1-thread-1] i.e.t.c.c.DecoratedMessageHandlerFactory : handled message io.eventuate.tram.springcloudcontractsupport.EventuateTramMessageVerifier 0000016f418024dc-14dae921faa80000

java.lang.IllegalStateException: Parsed JSON [{"orderDetails":{"lineItems":[{"quantity":5,"menuItemId":"1","name":"Chicken Vindaloo","price":{},"total":{}}],"orderTotal":{},"restaurantId":1,"consumerId":1511300065921},"restaurantName":"Ajanta"}] doesn't match the JSON path [$.['orderDetails'][?(@.['orderTotal'] == '61.70')]]

	at com.toomuchcoding.jsonassert.JsonAsserter.check(JsonAsserter.java:228)
	at com.toomuchcoding.jsonassert.JsonAsserter.checkBufferedJsonPathString(JsonAsserter.java:267)
	at com.toomuchcoding.jsonassert.JsonAsserter.isEqualTo(JsonAsserter.java:101)
	at org.springframework.cloud.contract.verifier.tests.MessagingTest.validate_orderCreatedEvent(MessagingTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by asn25** [comment]
One strange thing to add - when I run the single MessagingTest from Gradle, it fails (log is below):
(from /ftgo-order-service folder):
../gradlew cleanIntegrationTest integrationTest -DintegrationTest.single=MessagingTest
BUILD FAILED

But when I run Integration Tests in a bulk, they passed OK:
../gradlew cleanIntegrationTest integrationTest
BUILD SUCCEDED

Interesting, how it could be possible? 
Bulk Integration-tests-run should include MessagingTest-run...

====

../gradlew cleanIntegrationTest integrationTest -DintegrationTest.single=MessagingTest


org.springframework.cloud.contract.verifier.tests.MessagingTest > validate_orderCreatedEvent FAILED
    java.lang.IllegalStateException at MessagingTest.java:41
2019-12-26 16:49:58.811  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6f23efef: startup date [Thu Dec 26 16:49:49 MSK 2019]; parent: org.springframework.context.ann
otation.AnnotationConfigApplicationContext@64eff203
2019-12-26 16:49:58.815  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2019-12-26 16:49:58.816  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2019-12-26 16:49:58.816  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.i.channel.PublishSubscribeChannel    : Channel 'application-1.errorChannel' has 0 subscriber(s).
2019-12-26 16:49:58.816  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
2019-12-26 16:49:58.818  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-12-26 16:49:59.823  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-12-26 16:49:59.824  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed drop of schema as part of SessionFactory shut-down'
2019-12-26 16:49:59.826  INFO [ftgo-order-service,,,] 9432 --- [      Thread-12] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'

1 test completed, 1 failed

> Task :ftgo-order-service:integrationTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ftgo-order-service:integrationTest'.
> There were failing tests. See the report at: file:///C:/IdeaProjects/Microservices/ftgo-application/ftgo-order-service/build/reports/integrationTest/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 28s
34 actionable tasks: 5 executed, 29 up-to-date
